context:
  envName: ${CONTEXT_ENV_NAME:dev01}

spring:
  # Spring Data JPA
  data.mongodb:
    port: {REPOSITORY_PORT:27017}
    host: {REPOSITORY_HOST:localhost}

  # Spring Cloud Stream
  cloud:
    function.definition: generateTickerDataModel
    stream:
      bindings:
        # Input(s)
        generateTickerDataModel-in-0:
          destination: ${GENERATE_TICKER_DATA_MODEL_INPUT_0:myDefault}
        generateTickerDataModel-in-1:
          destination: ${GENERATE_TICKER_DATA_MODEL_INPUT_1:default}

      kafka.streams:
        bindings:
          generateTickerDataModel-in-0-consumer:
            applicationId: ${GENERATE_TICKER_DATA_MODEL_APP_ID_0}
            dlqName: ${GENERATE_TICKER_DATA_MODEL_DLQ_TOPIC_0}
          generateTickerDataModel-in-1-consumer:
            applicationId: ${GENERATE_TICKER_DATA_MODEL_APP_ID_1}
            dlqName: ${GENERATE_TICKER_DATA_MODEL_DLQ_TOPIC_1}

        binder:
          brokers: broker
          deserializationExceptionHandler: ${DESERIALIZATION_EXCEPTION_HANDLER:logAndFail} # Optional: logAndFail, sendToDlq, logAndSkip
          configuration:
            # Internal Topics
            replication.factor: ${INTERNAL_TOPIC_REPLICATION_FACTOR:3}
            # Broker Security
            ssl.endpoint.identification.algorithm: ${SECURITY_SSL_ENDPOINT_ID_ALGO}
            sasl.mechanism: ${SECURITY_SASL_MECHANISM}
            security.protocol: ${SECURITY_PROTOCOL}
            sasl.jaas.config: ${SECURITY_SASL_JAAS_CONFIG}
            # SerDes
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.springframework.kafka.support.serializer.JsonSerde